import numpy as np

def verify_zero_mean(npy_path: str):
    print(f"Loading embeddings from: {npy_path}")
    embeddings = np.load(npy_path)
    
    # Check dimensionality
    if embeddings.ndim != 2 or embeddings.shape[1] != 512:
        raise ValueError(f"Expected shape (N, 512), but got {embeddings.shape}")
        
    print(f"Successfully loaded {embeddings.shape[0]} embeddings.")

    # 1. Calculate the mean vector across the dataset
    mean_vector = np.mean(embeddings, axis=0)

    # 2. Calculate the magnitude (L2 norm) of the mean vector
    mean_magnitude = np.linalg.norm(mean_vector)

    # 3. Check the standard deviation
    actual_std = np.std(embeddings)
    theoretical_std = 1 / np.sqrt(512)

    # 4. Print the results
    print("\n--- Zero-Mean Assumption Verification ---")
    print(f"Magnitude of the Mean Vector: {mean_magnitude:.6f} (Ideal: 0.0)")
    print(f"Max absolute value in Mean:   {np.max(np.abs(mean_vector)):.6f}")

    print("\n--- Standard Deviation Check ---")
    print(f"Theoretical Max STD:          {theoretical_std:.6f}")
    print(f"Actual Dataset STD:           {actual_std:.6f}")
    
    diff = abs(theoretical_std - actual_std)
    print(f"Difference:                   {diff:.6f}")

    print("\n--- Interpretation ---")
    if mean_magnitude < 0.1 and diff < 0.001:
        print("Result: The zero-mean assumption holds beautifully.")
        print("The dataset is diverse enough that opposing facial vectors cancel each other out, keeping the center of mass near the origin.")
    else:
        print("Result: There is a center-shift in the latent space.")
        print("The vectors are clustered in a specific direction rather than being perfectly uniform across the hypersphere, which is common with datasets like FFHQ that have aligned, forward-facing constraints.")

if __name__ == "__main__":
    # Pointing to the master array generated by your script
    ARCFACE_MASTER_FILE = "/nas-ctm01/homes/dacordeiro/Face-DM/arcface_embeddings/Face-DM/ffhq256_deepface_arcface_retinaface_l2norm.npy"
    verify_zero_mean(ARCFACE_MASTER_FILE)
